config/routes.rb
Rails.application.routes.draw do
  get 'status/create'
  get 'statuses/create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  resources :todos, only: :index do
    resources :statuses, only: [:create, :edit, :update]
  end
  resources :statuses, only: [:index, :edit, :update]
  get 'statuses/:id/complete', to: 'statuses#complete', as: 'complete'

  root to: 'todos#index'
  devise_for :users, controllers: {
    registration: 'users/registration'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :statuses
  has_many :users, through: :statuses

  def todoadd?(user)
    statuses.where(user: user).any? ? true : false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :todos, through: :statuses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :alltodo
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name, :photo]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  private
  def alltodo
    @todos = Todo.all
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :findstatus, only: [:complete, :update, :edit]
  before_action :authenticate_user!

  def index
    @status = current_user.statuses
    @user = User.all
  end

  def create
    @todo = Todo.find(params[:todo_id])
    @status = Status.find_by(todo: @todo, user: current_user)
    if @starus == nil
      @starus = Status.create(todo: @todo, user: current_user)
    end
    if @starus.save
      redirect_to root_path, notice: 'Has completado esta tarea'
    else
      redirect_to root_path, alert: 'No se ha podido marcar como completada esta tarea'
    end
  end

  def edit
  end

  def update
    @status.update(status_params)
    redirect_to statuses_path
  end

  def complete
    @status.status = true
    @status.save
    redirect_to statuses_path
  end

  private
  def status_params
    params.require(:status).permit(:status)
  end

  def findstatus
    @status = Status.find(params[:id])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
  end

  def show
    @todo = Todo.find(params[:id])
    @user = User.all
    @starus = Status.all
    @s = Status.where(todo_id: params[:id], status: :true).limit(5).order(updated_at: :asc)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ToDo", root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Tareas realizadas #{current_user.statuses.where(status: true).count} / #{@todos.count} ", statuses_path, class:'nav-link' %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
            <%= current_user.email %>
          <% else %>
            Ingresar
          <% end %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <% if user_signed_in? %>
            <%= link_to "Edirar registro", edit_user_registration_path, class:'dropdown-item' %>
            <%= link_to "Salir", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
          <% else %>
            <%= link_to "Ingresar", new_user_session_path, class:'dropdown-item' %>
            <%= link_to "Registrar", new_user_registration_path, class:'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo de Septiembre</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    
    <%= yield %>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

app/views/statuses/create.html.erb
<h1>Statuses#create</h1>
<p>Find me in app/views/statuses/create.html.erb</p>

app/views/statuses/edit.html.erb
<div class="container seccion">
  <%= form_with model: @status, url: todo_status_path, local: true do |f| %>
    <div class="form-group form-check">
      <%= f.check_box :status, class:'form-check-input' %>
      <%= f.label :status, 'Estado tarea', class:'form-check-label' %>
    </div>
    <%= f.submit "Enviar", class:'btn btn-outline-primary' %>
  <% end %>
</div>

app/views/statuses/index.html.erb
<div class="container seccion">
  <div class="card-columns">
    <% @status.each_slice(3) do |row| %>
      <% row.each do |s| %>
        <div class="card">
          <%= image_tag s.todo.photo, class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= s.todo.name %></h5>
            <% if s.status == false %>
              <div class="d-flex justify-content-end">
                <%= link_to 'Listo', complete_path(s), class: 'btn btn-outline-success' %>
              </div>
            <% else %>
              <p class="card-text">Tarea Completada</p>
              <div class="d-flex justify-content-end">
                <%= link_to "Edit", edit_todo_status_path(id: s.id, todo_id: s.todo.id ), class:'btn btn-outline-warning' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="w-100"></div>
    <% end %>
  </div>
</div>

app/views/todos/index.html.erb
<div class="container seccion">
  <div class="card-columns">
    <% @todos.each_slice(3) do |row| %>
      <% row.each do |todos| %>
        <div class="card">
          <%= image_tag todos.photo, class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= todos.name %></h5>
            <% unless todos.todoadd?(current_user) %>
              <%= link_to 'Agregar tarea', todo_statuses_path(todos), class: 'btn btn-outline-success', method: :post %>
            <% else %>
              <%= link_to 'Tarea Agregada', statuses_path, class:'btn btn-outline-warning' %>
            <% end %>
            <%= link_to 'Ver detalle de tarea', todos, class:'btn btn-outline-primary' %>
          </div>
        </div>
      <% end %>
      <div class="w-100"></div>
    <% end %>
  </div>
</div>

app/views/todos/show.html.erb
<div class="container seccion">
  <div class="row">
    <div class="col">
      <h1><small>ToDo</small> <%= @todo.name %></h1>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <p>Usuarios que han agregado la tarea</p>
      <ul class="list-group">
        <% @todo.users.each do |u| %>
          <li class="list-group-item"><%= u.email %></li>
        <% end %>
      </ul>
    </div>
    <div class="col">
      <%# image_tag @todo.photo, class:'img-fluid' %>
      &nbsp;
    </div>
    <div class="w-100 p-4"></div>
    <div class="col">
     <p>Usuarios que han completado la tarea</p>
      <div class="row">
        <% @s.each_slice(4) do |row| %>
            <% row.each do |u| %>
              <div class="col-3">
                <div class="card">
                  <%= image_tag u.user.photo, class:'card-img-top' %>
                  <div class="card-body">
                    <p class="card-text"><%= u.user.name %><br><small><%= u.user.email %></small></p>
                  </div>
                </div>
              </div>
            <% end %>
          <div class="w-100"></div>
      <% end %>
      </div>
      
    </div>
    <div class="w-100"></div>
    <div class="col">
      <div class="d-flex justify-content-end">
        <%= link_to  "Volver", todos_path, class:'btn btn-outline-info' %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:'btn btn-link' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:'btn btn-link' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:'btn btn-link' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class:'btn btn-link' %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class:'btn btn-link' %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class:'btn btn-link' %><br />
  <% end -%>
<% end -%>